version: "3.3"
services:
  # MySQL container
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
      args:
        - MYSQL_VERSION=5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: raw_data
    ports:
      - "3306:3306"
  # Vertica container
  vertica:
    image: dataplatform/docker-vertica
    ports:
      - 5433:5433
    volumes:
      - ./vertica:/tmp/ddl
      - ./pyspark/spark2vertica/output:/tmp/input
  # Jupyter Notebook with pyspark
  pyspark-notebook:
    image: jupyter/pyspark-notebook
    build:
      context: ./pyspark
      dockerfile: Dockerfile
    volumes:
      - ./pyspark/spark2vertica:/home/jovyan/spark2vertica
    ports:
      - "8888:8888"
      - "4041:4041"
      - "4040:4040"
