version: "3.3"
services:
  # MySQL container
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
      args:
        - MYSQL_VERSION=5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: raw_data
    ports:
      - "3306:3306"
  # # Apache Airflow container
  # airflow:
  #   image: puckel/docker-airflow:1.10.4
  #   depends_on:
  #     - postgres
  #   environment:
  #     - LOAD_EX=n
  #     - EXECUTOR=Local
  #   volumes:
  #     - ./airflow/dags:/usr/local/airflow/dags
  #   ports:
  #     - "8080:8080"
  #   command: webserver
  #   healthcheck:
  #     test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3
  # # Postgres container for Airflow needs
  # postgres:
  #   image: postgres:9.6
  #   environment:
  #     - POSTGRES_USER=airflow
  #     - POSTGRES_PASSWORD=airflow
  #     - POSTGRES_DB=airflow
  # Vertica container
  vertica:
    image: dataplatform/docker-vertica
    ports:
      - 5433:5433
    volumes:
      - ./vertica/:/tmp/input
  # Jupyter Notebook with pyspark
  pyspark-notebook:
    image: jupyter/pyspark-notebook
    volumes:
      - ./support_data/notebooks:/home/jovyan/work
    ports:
      - "8888:8888"
      - "4041:4041"
      - "4040:4040"
